# K-MEANS CLUSTERING

## IMPORTING LIBRARIES

In [1]:
import cv2
import numpy as np

## ***READING IMAGE***

In [2]:
img=cv2.imread("d1.jpg")

In [3]:
img

array([[[  8,  48, 251],
        [  8,  48, 251],
        [  9,  49, 252],
        ...,
        [ 18,  56, 252],
        [ 17,  54, 252],
        [ 17,  54, 252]],

       [[  9,  49, 252],
        [  9,  49, 252],
        [  9,  49, 252],
        ...,
        [ 19,  57, 253],
        [ 18,  55, 253],
        [ 17,  54, 252]],

       [[  9,  49, 251],
        [ 10,  50, 252],
        [ 12,  50, 252],
        ...,
        [ 21,  57, 251],
        [ 19,  57, 253],
        [ 18,  56, 252]],

       ...,

       [[  3,  41, 253],
        [  3,  42, 251],
        [  4,  43, 252],
        ...,
        [ 12,  49, 255],
        [ 11,  48, 254],
        [ 10,  47, 253]],

       [[  3,  41, 253],
        [  4,  42, 254],
        [  4,  42, 254],
        ...,
        [ 11,  48, 254],
        [ 10,  47, 253],
        [  9,  46, 252]],

       [[  4,  41, 255],
        [  4,  41, 255],
        [  5,  42, 255],
        ...,
        [ 10,  46, 254],
        [  9,  45, 253],
        [  8,  44, 252]]

## ***RGB CONVERSION***

In [4]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

## ***RESHAPE***

In [5]:
vec=imgrgb.reshape((-1,3))
vec

array([[251,  48,   8],
       [251,  48,   8],
       [252,  49,   9],
       ...,
       [254,  46,  10],
       [253,  45,   9],
       [252,  44,   8]], dtype=uint8)

# ***FLOAT CONVERSION***

In [6]:
vec=np.float32(vec)
vec

array([[251.,  48.,   8.],
       [251.,  48.,   8.],
       [252.,  49.,   9.],
       ...,
       [254.,  46.,  10.],
       [253.,  45.,   9.],
       [252.,  44.,   8.]], dtype=float32)

## ***ITERATION TERMINATION CRITERIA*** 

In [7]:
criteria=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

## ***CLUSTER CONDITIONS***

In [8]:
k=3
attempts=100

## ***k-MEANS CLUSTERING***

In [9]:
compactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[248.14857 , 245.74104 , 244.41443 ],
       [247.97554 , 103.1898  ,  74.77726 ],
       [ 78.96074 ,  99.881386, 137.05501 ]], dtype=float32)

## ***UNIT CONVERSION***

In [10]:
center=np.uint8(center)
center

array([[248, 245, 244],
       [247, 103,  74],
       [ 78,  99, 137]], dtype=uint8)

##  ***FLATTENING AND  RESHAPENING***

In [11]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[247, 103,  74],
        [247, 103,  74],
        [247, 103,  74],
        ...,
        [247, 103,  74],
        [247, 103,  74],
        [247, 103,  74]],

       [[247, 103,  74],
        [247, 103,  74],
        [247, 103,  74],
        ...,
        [247, 103,  74],
        [247, 103,  74],
        [247, 103,  74]],

       [[247, 103,  74],
        [247, 103,  74],
        [247, 103,  74],
        ...,
        [247, 103,  74],
        [247, 103,  74],
        [247, 103,  74]],

       ...,

       [[247, 103,  74],
        [247, 103,  74],
        [247, 103,  74],
        ...,
        [247, 103,  74],
        [247, 103,  74],
        [247, 103,  74]],

       [[247, 103,  74],
        [247, 103,  74],
        [247, 103,  74],
        ...,
        [247, 103,  74],
        [247, 103,  74],
        [247, 103,  74]],

       [[247, 103,  74],
        [247, 103,  74],
        [247, 103,  74],
        ...,
        [247, 103,  74],
        [247, 103,  74],
        [247, 103,  74]]

## ***ORIGINAL AND SEGMENTED IMAGE*** 

In [12]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## ***MEAN SHIFT***

In [18]:
image=cv2.imread("d1.jpg")
#APPLY MEAN SHIFT SEGMENTATION
segmented_image=cv2.pyrMeanShiftFiltering(image,40,40)
#Display the segmented image
cv2.imshow('original_Image',image)
cv2.imshow('Segmented_Image',segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
